# Generated by Django 4.2.5 on 2023-10-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplicationhistory',
            name='loan_application',
        ),
        migrations.RemoveField(
            model_name='loanapplicationhistory',
            name='loanapplication_ptr',
        ),
        migrations.RemoveField(
            model_name='verificationdocument',
            name='loan_application',
        ),
        migrations.DeleteModel(
            name='LoanApplication',
        ),
        migrations.DeleteModel(
            name='LoanApplicationHistory',
        ),
        migrations.DeleteModel(
            name='VerificationDocument',
        ),
    ]
