# Generated by Django 4.2.5 on 2023-10-04 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_application', '0002_alter_loanapplication_customer_and_more'),
        ('core', '0002_remove_loanapplicationhistory_loan_application_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
