# Generated by Django 4.2.5 on 2023-10-04 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_loanapplicationhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='verifier',
        ),
        migrations.RemoveField(
            model_name='loanapplicationhistory',
            name='loan_application',
        ),
        migrations.RemoveField(
            model_name='loanapplicationhistory',
            name='loanapplication_ptr',
        ),
        migrations.RemoveField(
            model_name='verificationdocument',
            name='loan_application',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='LoanApplication',
        ),
        migrations.DeleteModel(
            name='LoanApplicationHistory',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='VerificationDocument',
        ),
    ]
