# Generated by Django 4.2.5 on 2023-10-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_role_id_employee_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(max_length=100),
        ),
    ]
