# Generated by Django 4.2.5 on 2023-10-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_application', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanApplicationHistory',
        ),
    ]
