# Generated by Django 4.2.5 on 2023-10-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('document_type', models.IntegerField()),
                ('file_path', models.CharField(max_length=100)),
                ('loan_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan_application.loanapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
