# Generated by Django 4.2.5 on 2023-10-04 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('customer', '0001_initial'),
        ('loan_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifier', to='employee.employee'),
        ),
    ]
