# Generated by Django 4.2.5 on 2023-10-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customer_datetime_updated_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='datetime_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='datetime_updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='datetime_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='datetime_updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='loanapplication',
            old_name='datetime_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='loanapplication',
            old_name='datetime_updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='datetime_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='datetime_updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='verificationdocument',
            old_name='datetime_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='verificationdocument',
            old_name='datetime_updated',
            new_name='date_updated',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role',
        ),
        migrations.AddField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='role',
            name='role_type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
