# Generated by Django 4.2.5 on 2023-10-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_datetime_created_customer_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='role_id',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='verification_status',
            field=models.IntegerField(default=0),
        ),
    ]
